cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: us-east-1

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB